name: untitled_goodreads_project
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.1
  xml2json: ^4.2.0
  google_fonts: ^1.1.0
  flutter_spinkit: ^4.1.2
  smooth_star_rating: 1.1.1
  animated_text_kit: ^2.2.0
  html: ^0.14.0+3
  flutter_widget_from_html: ^0.3.3+4
  provider: ^4.1.3
  cached_network_image: ^2.2.0+1
  flutter_show_more: ^0.1.2
  webview_flutter: ^0.3.22+1
  oauth1: ^1.0.4
  oauth1_client: ^1.0.0
  flutter_shine: ^0.0.5
  modal_bottom_sheet: ^0.1.6+1
  palette_generator: ^0.2.3
  sleek_circular_slider: ^1.1.0
  easy_web_view: ^1.3.0
  font_awesome_flutter: ^8.8.1
  flutter_rounded_progress_bar: ^0.1.2
  webview_flutter_plus: ^0.1.1+9
  url_launcher: ^5.5.0
  auto_size_text: ^2.1.0
  carousel_slider: ^2.2.1
  page_transition: ^1.1.6
  flutter_neumorphic: ^3.0.1
  fading_edge_scrollview: ^1.1.4
  material_design_icons_flutter: ^4.0.5345
  flutter_custom_clippers: ^1.1.1
  async: ^2.4.2
  fluttertoast: ^7.0.2
  shared_preferences: ^0.5.8
  fl_chart: ^0.11.0
  flutter_fadein: ^1.1.1
  flutter_barcode_scanner: ^1.0.1

  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  firebase_analytics: ^5.0.16
  firebase_core: ^0.4.5
  firebase_performance: ^0.3.2
  google_sign_in: ^4.5.1
#  firebase_crashlytics: ^0.1.4+1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


